spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: pguser
    password: pgadmin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # default
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: soumo
    password: supersection
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: F5D17E5B343E85EB122C7B404E635266556A586E3272358782F413F4428472B4B6250645367566B59703D85F2CF47E
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088